name : Shell Commands

on : 
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  # push:


  pull_request:
    types: [closed, assigned, opened, reopened]
    

jobs:
  run-Shell-Commands:
    runs-on : ubuntu-latest
    steps:
     - name : echo a string
       run : echo "Hello Jeevitha"
     - name : multiline script
       run : |
            node -v
            npm -v
     - name : python command
       run: |
           import platform
           print(platform.processor())
       shell: python

